Repository ninjadev/renin, pull requests merged in 2022-10, with the labels that each got.

#71 Upgrade dependencies
  renin/package.json
  renin/yarn.lock
Labels: hactoberfest-accepted

#69 Add 2d scene to example project
  example-project/src/FlatLand.ts
  example-project/src/SceneSwitcher.ts
  example-project/src/SpinningDonut.ts
Labels: hactoberfest-accepted, hacktoberfest-accepted

#76 Expand vertical clickable area on tracks
  renin/src/renin.ts
Labels: hacktoberfest-accepted

#77 Downgrade rollup to 2.x again
  renin/package.json
  renin/yarn.lock
Labels: hacktoberfest-accepted
